### ISSUE TITLE
replace ad-hoc makefiles and modules with a single python program

### ISSUE THREAD

**Issue by aepyornis** [aepyornis/nyc-db#10]
Let's take stock of the current situation. The database is current composed of 8 datasets, which use various languages:

| module| language |
| ------------- | ------------- |
| 311           | ruby  |
| acris          | makefile |
| dobjobs     | python |
| dof-sales    | python + shell |
| hpd-registrations | python + shell |
| hpd-violations      | shell | 
| pluto                     | python + shell |
| rent-stabilization   | python |

A little bit more than half rely on python, but they don't share much code. Moreover the download scripts are done in a a way that leave more to be desired such as ability to skip already downloaded files ,resume downloads, parallel importing, etc. 

Adding BBL, processing addresses, and downloading from open data are features that many off the  data importers could use.

**Comment by JoshuaAcosta** [comment]
@aepyornis have you (or anyone else) began working on this? How can I help?

**Comment by aepyornis** [comment]
@JoshuaAcosta I have, but I would love help.

check out out this folder: https://github.com/aepyornis/nyc-db/tree/master/src

If you install it: ``` cd src && make ```

It already has a interface that can upload 3 data sets: hpd-complaints, dob-complaints, and pluto via a cli tool: ``` python3 -m nycdb.cli --help ```

Today or Tomorrow I will write up a more detailed design notes document that will make it easier to contribute. In the meantime, don't hesitate to ping me with any questions!
