### ISSUE TITLE
dobjobs work types aren't being captured in postgres

### ISSUE THREAD

**Issue by lblok** [aepyornis/nyc-db#30]
They're in the original database as 'x' or null and the columns are defined as boolean, but everything appears null in the data so I don't think boolean is capturing it. Easy for me to change boolean to text type but if you want to do some transformation to the data to get it into postgres as true/false, that's beyond me right now.

**Comment by aepyornis** [comment]
good catch.  I think all we need to do is add 'x' into this list: https://github.com/aepyornis/nyc-db/blob/master/src/nycdb/typecast.py#L6
