### ISSUE TITLE
Get rid of tox.ini?

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#39]
I noticed there's a [`src/tox.ini`](https://github.com/aepyornis/nyc-db/blob/master/src/tox.ini) but tox doesn't appear to be used by Travis... I was also confused by it because it mentions Python 3.4, while the `.travis.yml` doesn't, which made me wonder what the earliest version of Python we supported was.

Anyhow, just thought I'd mention it!

**Comment by aepyornis** [comment]
I think that file is just a vestigate of some python project template genator to get started. Tox is usuful testing tool, but it's just as easy to let travis run the tests with multiple pyhton verison, so I think we can delete it.
