### ISSUE TITLE
Add a '--sql' option to dump the SQL of a dataset from its original CSVs/XLSs/etc

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#53]
I've been thinking of some ways to maintain a constantly-updated NYC-DB instance, and I'm realizing that one potential pipeline is really just to use `nycdb` (the command-line program) as a tool that downloads the datasets and translates them into SQL files, rather than directly communicating with a postgres instance. It could also be a potential workaround for #42, if that is actually a legitimate performance issue.

Having each dataset in its own SQL file would also give (advanced) users more control over how the data is loaded, since they could use `psql` to e.g. load a dataset in a single transaction, and so on.  It would also make it easy to parallelize the creation of multiple SQL files, if one has lots of compute resources to spare.

I am fairly noobish when it comes to databases of this size, though, so my thinking could be silly.

Anyways, I don't _think_ this should be hard to implement since it ought to just involve writing the `CREATE TABLE` and `INSERT` statements to a file rather than executing them on the database.

@aepyornis if I were to submit a PR that added such functionality, would you accept it?

**Comment by toolness** [comment]
Whoa, I did not know about `COPY`. Or Typecast, or the other stuff. Thanks!

Basically the problem I am trying to solve is just that I'd like to maintain an NYC-DB instance that continuously updates itself.  Right now one problem I have is that of having it be updated with as little downtime as possible, and I can think of two potential solutions:

1. Just point to a Postgres server via DNS.  Once every _n_ days, rebuild the whole NYC-DB in a new database server, and point DNS to it, then delete the old database server. This is similar to how the production deployment of a web app might work, and [AWS RDS seems to support it](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RenameInstance.html), though alternatively we could use EC2, or some non-AWS cloud provider.

2. Have a single database server that we update individual datasets of via atomic transactions.  This means that e.g. we could have a batch job that updates the `hpd_registrations` dataset by dropping the existing tables and populating new tables in a single atomic transaction, so that there's no observable period where the tables for the dataset appear to be empty or only partially populated.  It's this case where it seems like it might be useful to just have an SQL file of a dataset that I can dump into a DB as a transaction, but I guess another way to do it might be to add some support to `nycdb` to have it wrap everything it does in a single transaction (including dropping the dataset tables at the very beginning, if they exist).

But also, I am super rusty with databases so everything I just wrote could be ridiculous.

**Comment by aepyornis** [comment]
Thanks -- I understand what you are going for now.

Do note that by importing a sql file using psql -- ``` psql -d nycdb < hpd_violations.sql ``` -- you are not necessarily  executing the sql code inside a transaction. Depending how the pg_dump file has been configured, it typically drops the existing table with the same name, creates it, locks it, and then starts inserting the data. Trying to insert millions of rows inside a single transaction will likely give you [memory errors](https://dba.stackexchange.com/questions/206448/postgresql-large-transaction-oom-killer). 

Some thoughts on this problem:

If you only need it updated once a week, I'd go with the approach that you described in option 1. Automate the rebuilding of the database and then after it's ready, just swap the host variable in your production app configuration (fyi if ansible happens to be your automation tool of choice, this repo has an [ansible playbook](https://github.com/aepyornis/nyc-db/tree/master/ansible) that will setup a server with postgres ready to run nycdb)

These are the update frequencies of each dataset:

Daily:
- DOB Jobs
- DOB complaints
- HPD Violations
- OATH Hearings

Monthly
- HPD Registrations
- HPD Complaints
- Department of Finance Rolling Sales
- ACRIS

Yearly/never change:
- Pluto
- Tax Bills
- 2017 Marshal Evictions

So if you are looking to update NYCDB daily you only need to update 4 datasets every day (with a bigger update once a month).  A solution might be as simple as scripting nycdb to upload to those datasets with different table names (or in a different schema with the same name) and renaming the tables when they are ready.

**Comment by toolness** [comment]
Ahh this is super helpful, thanks!

Oy, I was worried about the massive transactions exhausting system resources. I like your idea about renaming the tables though, I think I'll do something involving that... Gonna close this issue now.

**Comment by aepyornis** [comment]
glad it was helpful :)
