### ISSUE TITLE
Should there be more indexes on "documentid" for ACRIS tables?

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#56]
Hello again!  I am still very new to all this, so I'm not sure if what I'm proposing is the right thing to do, but here goes...

According to a [NYC DOF document on the ACRIS dataset](https://github.com/fitnr/acris-download#acris-datasets):

> The "Document ID" in the master record is used to link all other record types to a master record. To find all of the lot (property) records associated with a master record, simply retrieve all records in the
property dataset with the same “Document ID” as the selected master record. The same process should be repeated for Party, Cross Reference and Remark records.

So it seems like the various tables are all related via the `documentid` column.

However, when I try looking up the parties involved in a document, by making a join between `real_property_master` and `real_property_parties` on `documentid`, it takes a _really_ long time.  Like a basic `SELECT * FROM real_property_parties WHERE documentid = 'blah'` takes maybe 30-60 seconds.

I also noticed that in [`acris.sql`](https://github.com/aepyornis/nyc-db/blob/0e6d2119171863358556ad69164dd795bbf65cbb/src/nycdb/sql/acris.sql), there's an index on `documentid` in `real_property_master`, but not in `real_property_parties`.  Should there basically be an index on this column in all the ACRIS tables?

**Comment by aepyornis** [comment]
totally. we should index that column. in general, the database is fairly light on the indexing.
