### ISSUE TITLE
Is ADDING_NEW_DATASETS.rst actually markdown?

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#58]
Hey, I noticed that some [documentation on adding new datasets](https://github.com/aepyornis/nyc-db/blob/45bef543e8746fe80c05378a94beec4a447940d5/src/ADDING_NEW_DATASETS.rst) was added in #57, which is awesome!  But it seems like it's Markdown rather than Restructured Text, as the `.rst` extension implies?

It also seems like it'd be useful to link to the document from the README maybe.

Should I issue a PR that makes these changes?

**Comment by aepyornis** [comment]
looks like markdown to me, but this is probably a question for @0xStarcat ⁉️

**Comment by aepyornis** [comment]
resolved by 078af48b85377e3028b0590a74aead69d9a8e2a2
