### ISSUE TITLE
Prefix tables with agency name

### ISSUE THREAD

**Issue by chrishenry** [aepyornis/nyc-db#7]
Currently, tables come in named after the type of data.

```
--------+-----------------+-------+----------
 public | all_violations  | table | deltanyc
 public | dobjobs         | table | deltanyc
 public | dof_sales       | table | deltanyc
 public | open_violations | table | deltanyc
 public | pluto_16v2      | table | deltanyc
```

It would be really helpful if they were prefixed with the agency name, both to avoid collisions and to help identify the source of the data.

For example, `hpd.all_violations`

**Comment by aepyornis** [comment]
done!
