### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by hnewberry** [aepyornis/nyc-db#99]
FYI, the websites SSL certificate is giving a cloud flare error. 

https://api.nycdb.info/ Error 526 Ray ID: 4c70e0214aeec5e2 • 2019-04-13 22:28:52 UTC
Invalid SSL certificate

**Comment by aepyornis** [comment]
hi @hnewberry thanks for the heads up. I just fix it!

by the way, that API is returning slightly older data, but I'm planning on updating it this week to be current.
